spring.application.name=P2P-Shopping
server.port=8081
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.uri=mongodb://localhost:27017/${MONGO_DB:p2p_shopping_mongo}
jwt.secret=${JWT_SECRET:defaultDevSecretKeyThatIsAtLeast32BytesLong!!}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

app.cors.allowed-origins=http://localhost:5173