spring.mongodb.uri=${MONGO_URI:mongodb://mongodb:27017/p2p_shopping_mongo}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=300000

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://ucart-smoky.vercel.app}
app.security.cookie-secure-flag=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

routing.api.base-url=${ROUTING_API_BASE_URL:https://api.openrouteservice.org}
routing.api.key=${ROUTING_API_KEY:}
